@startuml
'https://plantuml.com/class-diagram

package presentation{
    class Frame
    class Menu
}
package business{
    class Game
}

package data{
    class Score{
    }

}

Game --> Frame
Game .up. data

@enduml