@startuml
'https://plantuml.com/class-diagram

class Window{
    - startProgram()
}

class Program{
    - gp: GamePanel
    - mp: MenuPanel
    - startGameThread()
    - startMenuThread()
}

class GamePanel
class MenuPanel

Window --> Program
Program --> GamePanel
Program --> MenuPanel

@enduml